/**
 * EAS schema UIDs for Base Sepolia.
 *
 * Generated by `pnpm --filter @aval/scripts run register-schemas`.
 * Do not edit by hand — re-run the script and commit the result.
 */

import type { SchemaName } from "./index.js";

export type SchemaUidMap = Record<SchemaName, `0x${string}` | "">;

export const SCHEMA_UIDS: SchemaUidMap = {
  "WCK-Vendor": "0x8116d36ba09f2f0c16803a801d513e472bfb0f6729ecbdc73cf9210fa4fc0dd2",
  "WCK-Activation-Recipient": "0x4d46fa42adff572f7b9909870cc6ec334d5c5203558d45c99a62009e01666bd1",
  "WCK-Skill": "0x0996875d6ae633127cb5c7e781e5a779bfc444ad65255f0739df65a3558cee3b",
  "WCK-Supplier": "0xfb314378d2dbb8a9bce1b525d5377f00e56e800405f20732afbfcf544dde819e",
};

export function requireSchemaUid(name: SchemaName): `0x${string}` {
  const uid = SCHEMA_UIDS[name];
  if (!uid) {
    throw new Error(
      `EAS schema UID for "${name}" is not set. Run \`pnpm --filter @aval/scripts run register-schemas\` and commit packages/schemas/src/uids.ts.`,
    );
  }
  return uid;
}
