/**
 * Idempotently registers all four Aval EAS schemas on Base Sepolia and rewrites
 * `packages/schemas/src/uids.ts` with the resulting UIDs.
 *
 * The SchemaRegistry contract derives a schema's UID deterministically from
 * (schema, resolver, revocable). We compute that UID locally first, query
 * `getSchema(uid)` on-chain, and only send a registration tx when the registry
 * returns the zero record. That makes this script safe to re-run after a
 * partial failure — already-registered schemas are detected and skipped.
 *
 * Requires EAS_ISSUER_PRIVATE_KEY in .env. The issuer wallet pays gas; only a
 * tiny amount of Base Sepolia ETH is needed (~0.001 ETH covers all four).
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { type Hex, zeroAddress } from "viem";
import { SCHEMAS, SCHEMA_NAMES, type SchemaName } from "@aval/schemas";
import { publicClient, walletClientFromPrivateKey } from "./lib/chain.js";
import { REPO_ROOT, requirePrivateKey } from "./lib/env.js";
import {
  BASE_SEPOLIA_SCHEMA_REGISTRY,
  SCHEMA_REGISTRY_ABI,
  ZERO_BYTES32,
  deriveSchemaUid,
} from "./lib/schema-registry.js";

const UIDS_FILE = resolve(
  REPO_ROOT,
  "packages",
  "schemas",
  "src",
  "uids.ts",
);

type RegistrationResult = {
  name: SchemaName;
  uid: Hex;
  status: "already-registered" | "registered" | "verified";
  txHash?: Hex;
};

async function isRegistered(uid: Hex): Promise<boolean> {
  const client = publicClient();
  const record = await client.readContract({
    address: BASE_SEPOLIA_SCHEMA_REGISTRY,
    abi: SCHEMA_REGISTRY_ABI,
    functionName: "getSchema",
    args: [uid],
  });
  return record.uid !== ZERO_BYTES32;
}

async function registerOne(name: SchemaName): Promise<RegistrationResult> {
  const def = SCHEMAS[name];
  const resolver = def.resolver ?? zeroAddress;
  const expectedUid = deriveSchemaUid(def.schema, def.resolver, def.revocable);

  if (await isRegistered(expectedUid)) {
    return { name, uid: expectedUid, status: "already-registered" };
  }

  const wallet = walletClientFromPrivateKey(
    requirePrivateKey("EAS_ISSUER_PRIVATE_KEY"),
  );
  const account = wallet.account;
  if (!account) throw new Error("Wallet client missing account");

  const pub = publicClient();
  const { request } = await pub.simulateContract({
    address: BASE_SEPOLIA_SCHEMA_REGISTRY,
    abi: SCHEMA_REGISTRY_ABI,
    functionName: "register",
    args: [def.schema, resolver, def.revocable],
    account,
  });
  const txHash = await wallet.writeContract(request);
  const receipt = await pub.waitForTransactionReceipt({ hash: txHash });
  if (receipt.status !== "success") {
    throw new Error(
      `register(${name}) tx ${txHash} reverted on Base Sepolia.`,
    );
  }

  // OP Stack public RPCs can lag a few seconds after a write — retry before failing.
  let confirmed = false;
  for (let attempt = 0; attempt < 6; attempt++) {
    if (attempt > 0) await new Promise((res) => setTimeout(res, 2000));
    if (await isRegistered(expectedUid)) {
      confirmed = true;
      break;
    }
  }
  if (!confirmed) {
    throw new Error(
      `register(${name}) succeeded on-chain but getSchema(${expectedUid}) is still empty after retries.`,
    );
  }

  return { name, uid: expectedUid, status: "registered", txHash };
}

function renderUidsFile(uids: Record<SchemaName, Hex>): string {
  const lines = SCHEMA_NAMES.map(
    (name) => `  "${name}": "${uids[name]}",`,
  ).join("\n");
  return `/**
 * EAS schema UIDs for Base Sepolia.
 *
 * Generated by \`pnpm --filter @aval/scripts run register-schemas\`.
 * Do not edit by hand — re-run the script and commit the result.
 */

import type { SchemaName } from "./index.js";

export type SchemaUidMap = Record<SchemaName, \`0x\${string}\` | "">;

export const SCHEMA_UIDS: SchemaUidMap = {
${lines}
};

export function requireSchemaUid(name: SchemaName): \`0x\${string}\` {
  const uid = SCHEMA_UIDS[name];
  if (!uid) {
    throw new Error(
      \`EAS schema UID for "\${name}" is not set. Run \\\`pnpm --filter @aval/scripts run register-schemas\\\` and commit packages/schemas/src/uids.ts.\`,
    );
  }
  return uid;
}
`;
}

function writeUidsFile(results: RegistrationResult[]): void {
  const uids = Object.fromEntries(
    results.map((r) => [r.name, r.uid]),
  ) as Record<SchemaName, Hex>;
  writeFileSync(UIDS_FILE, renderUidsFile(uids));
}

async function main(): Promise<void> {
  console.log("Registering Aval EAS schemas on Base Sepolia");
  console.log(`SchemaRegistry: ${BASE_SEPOLIA_SCHEMA_REGISTRY}\n`);

  const results: RegistrationResult[] = [];
  for (const name of SCHEMA_NAMES) {
    process.stdout.write(`  ${name.padEnd(28)} ... `);
    const result = await registerOne(name);
    if (result.status === "already-registered") {
      console.log(`already registered (${result.uid})`);
    } else {
      console.log(`registered  ${result.uid}  tx ${result.txHash}`);
    }
    results.push(result);
  }

  writeUidsFile(results);
  console.log(`\nWrote ${UIDS_FILE}`);
  console.log("Commit packages/schemas/src/uids.ts to lock the UIDs.");
}

main().catch((err) => {
  console.error("\nregister-schemas failed:");
  console.error(err);
  process.exit(1);
});
